#!/usr/bin/env groovy

node {
    stage('checkout') {
        checkout scm
    }
    stage('build') {
        sh "./gradlew clean build"
    }
    stage('publish to Sonatype OSS Stage') {
        sh "./gradlew hms-kit:uploadArchives"
    }
}